[phases.setup]
cmds = [
    "apt-get update",
    "apt-get install -y ffmpeg libopus-dev libopus0 libsodium-dev"
]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[start]
cmd = "python main.py"
